### PR TITLE
Type fixes

### PR DESCRIPTION
**Pull request by lydell**
Hi!

Started using this package at work and ran into a couple of issues. What do you think of these solutions?

### Problem

1. It is not possible to do an idiomatic TS-import of this module without `esModuleInterop = true`.
2. Info is typed as `any`.
3. Tags are set as extra instead of tags in Sentry.
4. Extra metadata is not sent to Sentry.
5. Stack traces are generally missing in Sentry.

### Solution

1. Use regular exports instead of `export = ...`
2. Create type definition for info based on Winston and Sentry.
3. Use `scope.setTags` instead of `scope.setExtra`
4. Extract remaining properties from info and set using `scope.setExtras`
5. Always wrap the Winston message with `new Error(message)`

### Caveats

1. Breaking change: If you in js used `require("winston-transport-sentry-node")`, you now have to use `require("winston-transport-sentry-node").default`

### CODE REVIEW

**Comment by aandrewww** [comment]
Wow. A lot of work has been done.
I agree with all the problems and solutions.
Awesome 👏 
Thanks for your contribution 🙏

**Comment by lydell** [comment]
Wow, thanks for the quick merge! Will you publish this to npm?

**Comment by aandrewww** [comment]
Of course!
A new version of the package winston-transport-sentry-node (0.2.0) was published

you can use it :)
https://www.npmjs.com/package/winston-transport-sentry-node/v/0.2.0

**Comment by lydell** [comment]
Awesome, thanks! :100:

**Pull request merged**
