### PR TITLE
Add option to skip Sentry initialization

### PR DESCRIPTION
**Pull request by vuhrmeister**
Sentry may be initialized already at another place in the application. In that case it's better not to initialize it again, otherwise events get sent twice.

I'm open for discussion whether this is the right way or how we could solve that issue otherwise.

### CODE REVIEW

**Comment by chances** [comment]
@aandrewww This change would also benefit my use case: Logging is setup in a different module, outside the scope of app config.

**Comment by andrewda** [comment]
Another :+1: for this addition. Sentry is already configured within a separate Nest.js module, so the setup in `winston-transport-sentry-node` causes duplication.

**Comment by aandrewww** [comment]
thanks!

**Comment by aandrewww** [comment]
https://github.com/aandrewww/winston-transport-sentry-node/commit/cd10041533b1d732b05ed547845e397110eb7dc5

**Comment by aandrewww** [comment]
+ winston-transport-sentry-node@2.4.0

**Pull request merged**
