### PR TITLE
SentrySevertiy -> SentrySeverity typo fix

### PR DESCRIPTION
**Pull request by benbruscella**

### CODE REVIEW

**Comment by benbruscella** [comment]
@aandrewww any thoughts on merging this PR?

**Comment by aandrewww** [comment]
Thanks!
Merged

**Comment by benbruscella** [comment]
@aandrewww awesome! 

Could you please bump the npm package version too?

**Comment by aandrewww** [comment]
sure
winston-transport-sentry-node@2.5.1

**Pull request merged**
